services:
    ankerctl:
        image: anselor/ankerctl:exile-latest
        container_name: ankerctl
        restart: unless-stopped
        build: .

        # host-mode networking is required for pppp communication with the
        # printer, since it is an asymmetrical udp protocol.
        network_mode: host

        # bind to localhost by default
        environment:
            - FLASK_HOST=$FLASK_HOST
            - FLASK_PORT=$FLASK_PORT
        volumes:
            - $ANKERCTL_DATA:/root/.config/ankerctl

volumes:
    ankerctl_vol:
